% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created Tue Nov 01 14:49:31 IST 2016
%
% This script assumes these variables are defined:
%
%   train - input data.
%   output - target data.
% class 1- Male 20-30
s1=load('Male_20-30/Alpha/temp.txt');
i=1;
t1=double(173);
while i<174
    t1(i)=0;
    i=i+1;
end
 %class 2 - Male 10-20
 s2=load('Male_10-20/Alpha/temp.txt');
i=1;
t2=double(61);
while i<62
    t2(i)=1;
    i=i+1;
end
%class 3 - Male 0-10
 s3=load('Male_0-10/Alpha/temp.txt');
i=1;
t3=double(61);
while i<62
    t3(i)=2;
    i=i+1;
end

%class 4 - FeMale 20-30
 s4=load('Female_20-30/Alpha/temp.txt');
i=1;
t4=double(62);
while i<63
    t4(i)=0;
    i=i+1;
end

%class 5 - Female 10-20
 s5=load('Female_10-20/Alpha/temp.txt');
i=1;
t5=double(90);
while i<91
    t5(i)=1;
    i=i+1;
end

%class 6 - Female 0-10
 s6=load('Female_0-10/Alpha/temp.txt');
i=1;
t6=double(90);
while i<91
    t6(i)=2;
    i=i+1;
end

t1=t1';
t2=t2';
t3=t3';
t4=t4';
t5=t5';
t6=t6';

x = [s1;s2];
t = [t1;t2];
x=  [x;s3];
t=  [t;t3];
x=  [x;s4];
t=  [t;t4];
x=  [x;s5];
t=  [t;t5];
x=  [x;s6];
t=  [t;t6];

x=x';

tt=t;
t=t';
inputs={ 4801.19 4523.32 4837.38 4829.51 4211.32 4828.31 4807.53 4471.21 4685.93 4215.79 4517.41 5075.16 4498.99 4346.65 
};
% Create a Pattern Recognition Network
hiddenLayerSize = 100;
net = patternnet(hiddenLayerSize);

in=inputs';

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;


% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
tind = vec2ind(t);
yind = vec2ind(y);
percentErrors = sum(tind ~= yind)/numel(tind);
performance = perform(net,t,y)

%o=net(in);
%display(o)
%display(performance);
%gensim(net)
% View the Network
%view(net)
% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, plotconfusion(t,y)
%figure, plotroc(t,y)
%figure, ploterrhist(e)

